import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronRight, PackageCheck } from 'lucide-react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { CATALOG_ROOT, CatalogNode, catalogPath, findCatalogPath } from '../data/catalog';

const Breadcrumbs: React.FC<{ ancestors: CatalogNode[] }> = ({ ancestors }) => <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1.5 text-sm text-[#0A1930]/65"><Link className="font-semibold hover:text-[#d86f21]" to="/">Home</Link><ChevronRight className="h-3.5 w-3.5" /><Link className="font-semibold hover:text-[#d86f21]" to="/products">Products</Link>{ancestors.map((ancestor, index) => <React.Fragment key={ancestor.slug}><ChevronRight className="h-3.5 w-3.5" />{index === ancestors.length - 1 ? <span className="font-semibold text-[#0A1930]" aria-current="page">{ancestor.title}</span> : <Link className="font-semibold hover:text-[#d86f21]" to={catalogPath(ancestors.slice(0, index + 1))}>{ancestor.title}</Link>}</React.Fragment>)}</nav>;

const CatalogHero: React.FC<{ node?: CatalogNode; root?: boolean; ancestors?: CatalogNode[] }> = ({ node, root, ancestors = [] }) => {
  const title = root ? 'Packaging that fits the product, the shelf, and the journey.' : node!.title;
  const subtitle = root ? 'Product catalogue' : node!.subtitle;
  const description = root ? 'Explore structures and supplies through practical formats, clear specifications, and custom production options.' : node!.description;
  const image = root ? '/images/hero/sustainable-retail-studio.png' : node!.image;
  return <section className={`relative isolate overflow-hidden bg-[#0A1930] text-white ${root ? 'min-h-[100svh]' : 'min-h-[50svh]'}`}><img src={image} alt={root ? 'Custom packaging formats arranged in a studio' : `${node!.title} packaging`} fetchPriority={root ? 'high' : 'auto'} className="absolute inset-0 -z-20 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#081426]/90 via-[#081426]/65 to-[#081426]/25" /><div className={`relative mx-auto flex max-w-7xl items-end px-4 sm:px-6 lg:px-8 ${root ? 'min-h-[100svh] pb-16 pt-36' : 'min-h-[50svh] pb-14 pt-32'}`}><div className="max-w-3xl">{!root && <div className="mb-8 rounded bg-white/95 px-3 py-2"><Breadcrumbs ancestors={ancestors} /></div>}<p className="text-xs font-bold uppercase tracking-[0.18em] text-[#FFB35C]">{subtitle}</p><h1 className={`font-heading mt-4 font-bold leading-[1.03] ${root ? 'text-5xl sm:text-6xl lg:text-7xl' : 'text-5xl sm:text-6xl'}`}>{title}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-white/85 sm:text-lg">{description}</p>{root && <a href="#catalogue" className="mt-8 inline-flex items-center gap-2 border-b-2 border-[#FF9933] pb-1 text-sm font-bold text-white hover:text-[#FFB35C]">Explore product categories <ArrowRight className="h-4 w-4" /></a>}</div></div></section>;
};

const CatalogCard: React.FC<{ node: CatalogNode; path: string; viewMore?: boolean }> = ({ node, path, viewMore }) => <Link to={path} className="group block overflow-hidden border border-[#0A1930]/15 bg-[#fffdf8] transition duration-300 hover:-translate-y-1 hover:border-[#d86f21]/60 hover:shadow-[0_14px_30px_rgba(10,25,48,0.12)]"><div className="relative overflow-hidden"><img src={node.image} alt={viewMore ? `Explore all ${node.title} categories` : `${node.title} packaging`} loading="lazy" className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" />{viewMore && <div className="absolute inset-0 flex items-center justify-center bg-[#0A1930]/60 p-5 text-center"><span className="catalog-view-more-label font-heading text-3xl font-bold text-white drop-shadow-sm">View More</span></div>}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d86f21]">{viewMore ? 'Full range' : node.subtitle}</p><h3 className="font-heading mt-2 text-2xl font-bold text-[#0A1930]">{viewMore ? `All ${node.title} Categories` : node.title}</h3><p className="mt-2 text-sm leading-relaxed text-[#0A1930]/65">{viewMore ? `Browse every ${node.title.toLowerCase()} category and format.` : node.description}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#0A1930]">Explore <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></div></Link>;

const ProgressiveCards: React.FC<{ nodes: CatalogNode[]; ancestors: CatalogNode[]; title: string }> = ({ nodes, ancestors, title }) => {
  const [visible, setVisible] = useState(5); const sentinel = useRef<HTMLDivElement>(null);
  useEffect(() => { setVisible(5); }, [nodes]);
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) setVisible((value) => Math.min(value + 5, nodes.length)); }, { rootMargin: '300px' }); const element = sentinel.current; if (element) observer.observe(element); return () => observer.disconnect(); }, [nodes.length]);
  return <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d86f21]">Explore the range</p><h2 className="font-heading mt-2 text-4xl font-bold">{title}</h2></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{nodes.slice(0, visible).map((child) => <CatalogCard key={child.slug} node={child} path={catalogPath([...ancestors, child])} />)}</div>{visible < nodes.length && <div ref={sentinel} className="py-8 text-center text-sm font-semibold text-[#0A1930]/60">Loading more categories…</div>}</section>;
};

const LeafDetails: React.FC<{ node: CatalogNode }> = ({ node }) => <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d86f21]">Product features</p><h2 className="font-heading mt-2 text-4xl font-bold">Designed around your product.</h2><div className="mt-7 space-y-4">{node.features?.map((feature) => <p key={feature} className="flex gap-3 border-b border-[#0A1930]/10 pb-4 font-semibold"><Check className="h-5 w-5 shrink-0 text-[#d86f21]" />{feature}</p>)}</div><p className="mt-8 text-sm font-bold uppercase tracking-[0.14em] text-[#d86f21]">Applications</p><div className="mt-3 flex flex-wrap gap-2">{node.applications?.map((application) => <span key={application} className="border border-[#0A1930]/15 bg-[#f2eee7] px-3 py-2 text-sm font-semibold">{application}</span>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d86f21]">Specifications</p><h2 className="font-heading mt-2 text-4xl font-bold">Made to specification.</h2><dl className="mt-7 divide-y divide-[#0A1930]/10 border-y border-[#0A1930]/10">{node.specifications?.map(({ label, value }) => <div key={label} className="grid grid-cols-[minmax(110px,.6fr)_1.4fr] gap-4 py-4 text-sm"><dt className="font-bold">{label}</dt><dd className="text-[#0A1930]/70">{value}</dd></div>)}</dl><Link to="/request-quote" className="mt-8 inline-flex items-center gap-2 bg-[#FF9933] px-6 py-3 font-bold text-[#0A1930] hover:bg-[#FFB35C]">Request a quote <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>;

export const CatalogIndexPage: React.FC = () => <div className="bg-[#f2eee7] text-[#0A1930]"><CatalogHero root /><section id="catalogue" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d86f21]">Product families</p><h2 className="font-heading mt-2 text-4xl font-bold">Explore the catalogue.</h2></div><div className="space-y-16">{CATALOG_ROOT.map((family, index) => <section key={family.slug} className="border-t border-[#0A1930]/10 pt-12"><div className={`grid gap-8 lg:grid-cols-2 lg:items-stretch ${index % 2 ? 'lg:[&>div:first-child]:order-2' : ''}`}><div className="flex min-h-72 flex-col justify-center sm:min-h-96"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d86f21]">{family.subtitle}</p><h2 className="font-heading mt-3 text-5xl font-bold">{family.title}</h2><p className="mt-4 max-w-xl leading-relaxed text-[#0A1930]/70">{family.description}</p></div><img src={family.image} alt={`${family.title} packaging`} loading="lazy" className="h-72 w-full object-cover sm:h-96" /></div><div className="mt-9"><h3 className="font-heading text-2xl font-bold">Available {family.title} Categories</h3><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{family.children?.slice(0, 2).map((child) => <CatalogCard key={child.slug} node={child} path={catalogPath([family])} />)}<CatalogCard node={family} path={catalogPath([family])} viewMore /></div></div></section>)}</div></section></div>;

export const CatalogNodePage: React.FC = () => { const { '*': splat = '' } = useParams(); const match = findCatalogPath(splat.split('/').filter(Boolean)); if (!match) return <Navigate to="/products" replace />; const { node, ancestors } = match; return <div className="bg-[#f2eee7] text-[#0A1930]"><CatalogHero node={node} ancestors={ancestors} />{node.children?.length ? <ProgressiveCards nodes={node.children} ancestors={ancestors} title={`Available ${node.title} Categories`} /> : <LeafDetails node={node} />}<section className="border-t border-[#0A1930]/10 bg-[#dff4f1]"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-7 sm:px-6 lg:px-8"><PackageCheck className="h-6 w-6 shrink-0 text-[#d86f21]" /><p className="font-semibold">Need help choosing the right format? Share your product dimensions, quantity, artwork, and delivery timeline.</p></div></section></div>; };
export const CatalogFamilyPage = CatalogNodePage;
export const CatalogItemPage = CatalogNodePage;
